---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Add repository
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    - name: Install nginx
      ansible.builtin.yum:
        name:
          - nginx
        state: present
      notify: enable nginx
    - name: create var/www/data folder
      ansible.builtin.file:
        path: "/var/www/data"
        state: directory
        mode: "0755"
        setype: httpd_sys_content_t
    - name: create index.html
      ansible.builtin.template:
        src: "index.html.j2"
        dest: "/var/www/data/index.html"
        setype: httpd_sys_content_t
    - name: create nginx config from template
      ansible.builtin.template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/conf.d/default.conf"
      notify: restart nginx

  handlers:
    - name: enable nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
